### ISSUE TITLE
ImportError: cannot import name 'ResNetUNet' from 'model' (unknown location)

### ISSUE THREAD

**Issue by seekingdeep** [SakuraRiven/DCLNet#1]
@SakuraRiven hi there,

i am getting error when trying to predict:
```
(mmdet) home@home-lnx:~/programs/DCLNet$ CUDA_VISIBLE_DEVICES=0 python detect.py
Traceback (most recent call last):
  File "detect.py", line 11, in <module>
    from model import ResNetUNet
ImportError: cannot import name 'ResNetUNet' from 'model' (unknown location)
```

i already copied the `dcn` folder from `github.com/MhLiao/DB/tree/master/assets/ops/dcn`

**Comment by SakuraRiven** [comment]
Sorry the `model` dir is uploaded just now

**Comment by seekingdeep** [comment]
hmmm, i am constantly getting bugs.
each time i fix one, then another bug appears.

**Comment by rmast** [comment]
dependency https://github.com/MhLiao/DB appears to depend on cuda as it has no cpu implementation for some parts:
https://github.com/MhLiao/DB/blob/master/assets/ops/dcn/functions/deform_conv.py#L41 "raise NotImplementedError"
